[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tempfile = "3.14.0"

[dependencies]
clap = { version = "3", features = ["derive"] }
mockall = "0.11"
predicates = "2.0"
rand = "0.8"