name: CI tests for Lab2

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
        run: npm install
        working-directory: ./lab2
    
    - name: Run tests
        run: npm test
        working-directory: ./lab2
